version: "3.9"
services:

  mariadb:
    image: docker.io/mariadb:10
    container_name: car_shop_mariadb
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: mariadb
      MARIADB_ROOT_PASSWORD: mariadb
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
    ports:
      - "3306:3306"